model_list:
  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: bedrock_converse/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      
litellm_settings:
  drop_params: true
  set_verbose: true